### ISSUE TITLE
Does this tool have threading for faster process?

### ISSUE THREAD

**Issue by cr4shcod3** [ThoughtfulDev/EagleEye#27]
I don't know if there's threading in this tool but it seems like the process is slow. Is it normal?

**Comment by ThoughtfulDev** [comment]
No threading. Only one instance of FF is open at a time, since some processes depend on each other.

**Comment by cr4shcod3** [comment]
The process like finding image and the reverse image search part. I hope you can find a way to add threading or threading argument in argparse

**Comment by ThoughtfulDev** [comment]
The problem is that I use one list for storing the images and scraped links.

Using threading would mean that each thread would have its own list which have to be unified at the end (or one global list which has to be thread save).


Practically I doubt that using threads would speed up the process.
You can always try to implement threading. Pull requests are welcome :smiley:


(this text may have some spelling mistakes since I'm on mobile)

**Comment by cr4shcod3** [comment]
Ok I will try to implement threading on this. Later after I publish the v2 of my tool too. You can now close this
